name: CI/CD PoC Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build backend Docker image
        run: |
          cd backend
          docker build -t parking-backend:latest .

      - name: Build frontend Docker image
        run: |
          cd frontend
          docker build -t parking-frontend:latest .

  simulate-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run backend and frontend containers
        run: |
          docker run -d --name backend -p 5000:5000 parking-backend:latest
          docker run -d --name frontend -p 3000:3000 parking-frontend:latest
          echo "Containers are running! Backend on port 5000, Frontend on port 3000"
